// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "QuickDrop",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "QuickDrop",
            targets: ["App"],
            bundleIdentifier: "com.ankit.filedrop.ios",
            teamIdentifier: "VKFJ35CNQS",
            displayVersion: "1.1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .incomingNetworkConnections(),
                .outgoingNetworkConnections(),
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .localNetwork(purposeString: "QuickDrop needs local network access to find nearby devices.", bonjourServiceTypes: ["_http._tcp"]),
                .photoLibrary(purposeString: "QuickDrop needs access to your photos to send them to other devices.")
            ],
            appCategory: .utilities,
            additionalInfoPlistContentFilePath: "AppInfo.plist"
        )
    ],
    dependencies: [
        .package(url: "https://github.com/yene/GCDWebServer.git", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                .product(name: "GCDWebServer", package: "GCDWebServer")
            ],
            path: "Sources"
        )
    ]
)